### ISSUE TITLE
grafana cloud: ECONNREFUSED error

### ISSUE THREAD

**Issue by AlessioGr** [Julien-R44/pino-loki#16]
I'm getting the following error:
`Attempting to send log to Loki failed. Got an axios error, error code: 'ECONNREFUSED' message: connect ECONNREFUSED ::1:80`

Both locally and when it's deployed on a real server. Has anyone experienced a similar issue? Do I maybe need to configure something in grafana cloud? 

This is how I set it up in pino:
```ts
{
  target: 'pino-loki',
  options: {
    options: {
      batching: false,
      host: 'https://logs-prod-012.grafana.net',
      basicAuth: {
        username: "602xxx",
        password: "xxxxxxxxxxx", //api key
      },
    },
  },
  level: null,
}
```

## Versions
"pino-loki": "^2.0.4",
"pino": "^8.14.1",
"express": "^4.18.2",

**Comment by Julien-R44** [comment]
You have twice the "options" key, one nested in the other 

```ts
 options: {
    options: {
```

**Comment by AlessioGr** [comment]
> You have twice the "options" key, one nested in the other
> 
> ```ts
>  options: {
>     options: {
> ```

Oh wow, how could I miss that! That's the problem with untyped code haha.

Thank you! It works now!

**Comment by Julien-R44** [comment]
Yeah! I am currently working on the next version that will ship a specific interface that could be manually added for typing this

**Comment by Julien-R44** [comment]
Added a little utility type for defining pino loki options : 

```ts
import pino from 'pino'
// 👇
import type { LokiOptions } from 'pino-loki'

const transport = pino.transport<LokiOptions>({
  target: "pino-loki",
  options: {
    // ...
  },
});

const logger = pino(transport);
```
