### ISSUE TITLE
How to properly create log messages?

### ISSUE THREAD

**Issue by paradix** [Julien-R44/pino-loki#2]
Why does the logging sends 
```
JSON.stringify(item.data)
```
in the stream to loki

https://github.com/Julien-R44/pino-loki/blob/0b99d33ce46821c5ae1d11b727678db274c94369/src/loki.js#L32

In my case this results in a null message in my grafana loki 
![image](https://user-images.githubusercontent.com/3265277/158697095-c23e1f10-307d-4105-9bc4-d2fe490e0232.png)

After changing this line to 
```
JSON.stringify(item)
```
I finally get proper logs
![image](https://user-images.githubusercontent.com/3265277/158697253-074e9670-efc1-4954-a11b-7b614170f505.png)

**Comment by Julien-R44** [comment]
Yup, it does indeed look like a bug. Are you using the lib or the CLI version? 

I advise you to fork the library and use your version for now. 

Currently I don't have time at all, too much work you know, but in 2 or 3 weeks I'll totally rewrite the library in Typescript + ESM and add some tests.

There are also a lot of features missing, especially the authorization part, I will take the opportunity to add all that ! 👍

**Comment by Givemeurcookies** [comment]
I can also confirm this bug when testing.

> There are also a lot of features missing, especially the authorization part, I will take the opportunity to add all that ! +1

This will be a bit off-topic related to the bug report:
I checked auth a bit when I was adding some of the error handling and from the Loki docs `Grafana Loki does not come with any included authentication layer. Operators are expected to run an authenticating reverse proxy in front of your services, such as NGINX using basic auth or an OAuth2 proxy.` Do you have any ideas on how to implement this on the client? I've done some work on things in the past and the best way I've found is allowing an option where users can "inject" their authentication solution into the request. Maybe have a few samples with i.e basic auth.

There's also the question about improving the library with GRPC. GRPC is often used with internal systems (not in browsers) and drastically decreases the request overhead, is faster, is less error prone + provides request order guarantees (no issues with timestamp exceptions when only connected with one client). Grafana Loki supports GRPC and other libraries that I've researched use GRPC.

I'd be happy to contribute (if I get the time) - if there's any interest for that it'd probably be best to open a new thread to discuss potential features.

**Comment by Julien-R44** [comment]
> This will be a bit off-topic related to the bug report: I checked auth a bit when I was adding some of the error handling and from the Loki docs `Grafana Loki does not come with any included authentication layer. Operators are expected to run an authenticating reverse proxy in front of your services, such as NGINX using basic auth or an OAuth2 proxy.` Do you have any ideas on how to implement this on the client? I've done some work on things in the past and the best way I've found is allowing an option where users can "inject" their authentication solution into the request. Maybe have a few samples with i.e basic auth.

That's basically that. We just need to offer some options for the client that will eventually be forwarded to axios for the call to Loki. So either Basic auth, or via an Authorization Header.

> 
> There's also the question about improving the library with GRPC. GRPC is often used with internal systems (not in browsers) and drastically decreases the request overhead, is faster, is less error prone + provides request order guarantees (no issues with timestamp exceptions when only connected with one client). Grafana Loki supports GRPC and other libraries that I've researched use GRPC.
> 
> I'd be happy to contribute (if I get the time) - if there's any interest for that it'd probably be best to open a new thread to discuss potential features.

Yeah that would be super cool to have that. In priority I will rewrite a good part of the library as mentioned above. Once that's done, I think we can tackle the gRPC part. If at this time, you are available and you want to, I can let you take care of this part, it will be with pleasure.
Thanks a lot for your proposal. 🙂

**Comment by Anton1337** [comment]
If i submit a PR for the `JSON.stringify(item)`, will you merge and update?

**Comment by Julien-R44** [comment]
Yes, of course. But please make sure that the CLI mode still works with this modification. Thank you very much !

**Comment by Julien-R44** [comment]
The bug has been fixed and the library rewritten from-scratch in Typescript with some new features added in the process.

gRPC will come in the next days/weeks !
