### ISSUE TITLE
Is there a way to use API key as auth

### ISSUE THREAD

**Issue by Suniron** [Julien-R44/pino-loki#25]
Hey there,

I'm using Loki from the **Scaleway Cockpit** and I haven't a username + password but just an API key.

For example, i can send a log by CURL by this way:

```
curl --location 'https://logs.cockpit.fr-par.scw.cloud/loki/api/v1/push' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer myApiKeyHere' \
--data '{
  "streams": [
    {
      "stream": {
        "label": "helloWorld"
      },
      "values": [
          [ "1706107899000000000", "This is a basic log :-)" ]
      ]
    }
  ]
}'
```

So, is there a way to use the API key as auth instead of credentials?

**Comment by Julien-R44** [comment]
You should be able to use `headers` options : https://github.com/Julien-R44/pino-loki#headers

```ts
import type { LokiOptions } from '../src/types/index'

const transport = pino.transport<LokiOptions>({
  target: 'pino-loki',
  options: {
    headers: {
      'Authorization': `Bearer ${process.env.LOKI_TOKEN}`,
    },
  },
})
```

**Comment by Suniron** [comment]
Yes, sorry because i wanted to delete this POST since i saw in the documentation that we can also put the API KEY directly in the URL..

Thank's for your help!
