### ISSUE TITLE
[Question] write to grafana cloud + stdout (ie console) simultaneously?

### ISSUE THREAD

**Issue by rcornacchia** [Julien-R44/pino-loki#28]
Package works great, thanks for writing this!

Wondering if it's possible to write to both stdout (ie pino-pretty) and grafana cloud simultaneously. Thanks in advance

**Comment by Julien-R44** [comment]
Yup. See https://github.com/Julien-R44/pino-loki/blob/dev/examples/multiple_transports.ts

**Comment by Julien-R44** [comment]
Also see the pino documentation : https://getpino.io/#/docs/transports?id=v7-transports

![image](https://github.com/Julien-R44/pino-loki/assets/8337858/4efff2f3-00d9-4cb6-b355-664920f4e9b2)

**Comment by rcornacchia** [comment]
awesome, thanks for the quick response!
