### ISSUE TITLE
Pass custom labes

### ISSUE THREAD

**Issue by benjibenoit** [Julien-R44/pino-loki#38]
Hi,

I'm trying to pass custom labels like :
```ts
logger.info(
    { traceId: this.signature },
        `Transaction ${this.signature} has types: ${this.type}`
    )
```
And get this label in grafana but "traceId" is not showing :
![image](https://github.com/user-attachments/assets/2cfffa07-ad6f-4b9c-91e2-90b279eaf608)

Do you know how to do?

**Comment by Julien-R44** [comment]
https://github.com/Julien-R44/pino-loki#propstolabels
