### ISSUE TITLE
Coalesce throw an error

### ISSUE THREAD

**Issue by Livaa** [Julien-R44/pino-loki#4]
It appears that line 84 from index.cjs throw the following Syntax error:

`services/node_modules/pino-loki/dist/index.cjs:84
options.timeout ?? (options.timeout = 3e4);

SyntaxError: Unexpected token '?'`

**Comment by Julien-R44** [comment]
Logical null assignment is only supported in Node 15 and above. I guess you are using a lower version?

I recommend you to upgrade your Node version if possible !

**Comment by Livaa** [comment]
updating nodejs fixed it, thanks.
