### ISSUE TITLE
X-Scope-OrgID support

### ISSUE THREAD

**Issue by Mahamed-Belkheir** [Julien-R44/pino-loki#5]
Currently there's no way to pass an X-Scope-OrgID header to send with requests to loki, which is required when using it in Multi-tenancy mode, which is the case if you're using Grafana Cloud, I need this feature so I will be forking and patching this in, and then making a PR, opening this issue incase someone else is running into the same issue currently

**Comment by Julien-R44** [comment]
Added support for custom headers through the `headers` key, so you should be able to pass your X-Scope-Org-Id here :

```ts
const transport = pino.transport<LokiOptions>({
  target: 'pino-loki',

  options: {
    headers: {
      'X-Scope-OrgID': 'your-id'
    },
    
    // ...
   }
})
```

Available in 2.1.0
