### ISSUE TITLE
How to use the plugin with Grafana Cloud

### ISSUE THREAD

**Issue by enricopolanski** [Julien-R44/pino-loki#6]
Hello.

I have been trying to understand how to send logs with pino-loki straight to Grafana Cloud (I have no local instance of Loki installed on my production or environment machines) but so far I don't really understand if the use case is supported or not or if I need to default to using promtail.

**Comment by Julien-R44** [comment]
Hello!

I myself have tested with Grafana Cloud successfully with the following parameters : 

```ts
{
	  host: "https://logs-prod-eu-west-0.grafana.net",
	  basicAuth: {
	    username: "181770",
	    password: "apiKey",
	  },
}
```

These values can be found on the Loki details page on Grafana cloud :

![image](https://user-images.githubusercontent.com/8337858/179701471-031a07ba-916f-4a98-8836-fdc6d40c50ab.png)

And regarding the API key, you will have to create one from your "my account" page on grafana.net and use it as password in "basicAuth" object.

Feel free to reopen the issue if needed

**Comment by paradix** [comment]
@Julien-R44  Is it still working that way? I can't make it work with Grafana Cloud. The password should be thie base64 encoded string that Grafana Cloud calls API Key?

**Comment by lesimoes** [comment]
> @Julien-R44 Is it still working that way? I can't make it work with Grafana Cloud. The password should be thie base64 encoded string that Grafana Cloud calls API Key?

Works well in 2023! I'm using pino-http too and does not need to convert to Base 64.


` 
    pinoHttp: {
      name: version,
      level: 'info',
      transport: {
        target: 'pino-loki',
        options: {
          singleLine: true,
          messageFormat: '[{context}] {msg}',
          ignore: 'context',
          colorize: true,
          labels: { application: 'nest-app' },
          host: process.env.LOKI_HOST,
          basicAuth: {
            username: process.env.LOKI_USER,
            password: process.env.LOKI_PASSWORD,
          },
        },
      },
      genReqId: () => randomUUID(),
    }
`

**Comment by paradix** [comment]
Turns out I had some errors in my config. Thanks @lesimoes for the confirmation. I had again a look and found the problem at least ;)
