### ISSUE TITLE
Logs aren't sent before process exits

### ISSUE THREAD

**Issue by Givemeurcookies** [Julien-R44/pino-loki#7]
When I was testing sending data programmatically in a process without a listener the last logs never arrived to Loki.

If I'm not mistaken - in Node.js the behaviour is that the process exits after there's no more event listeners, port listeners or interval/timeouts.

The fact that a process can exit without sending logs is fairly critical as it may also mean that any fatal errors won't be logged.

**Comment by Julien-R44** [comment]
Thanks for the feedback. Could you please provide a reproduction? I don't seem to have any problems on my end

**Comment by Julien-R44** [comment]
Fixed with 2.1.0 🙂 Sorry for taking so long

Feel free to reopen if issue persist
