### ISSUE TITLE
Error when running npx pino-loki (Missing shebang in cli.cjs?)

### ISSUE THREAD

**Issue by LonelessCodes** [Julien-R44/pino-loki#9]
OS: Ubuntu 22.04
Node: v18.12.1
NPM: 8.19.2

When trying to pipe stdout from my app (with pino logging) into pino-loki like `node app.js | npx pino-loki --hostname localhost:3100`, I get an error similar to the following. Same error when i just run it standalone with npx, without piping:

```
me@pc:~/project$ npx pino-loki --help
~/project/node_modules/.bin/../pino-loki/dist/cli.cjs: 1: use strict: not found
~/project/node_modules/.bin/../pino-loki/dist/cli.cjs: 3: Syntax error: word unexpected (expecting ")")
```

My investigation brought me to the conclusion a shebang for node was missing in dist/cli.cjs. After I added that to the beginning of the file everything worked.

```javascript
--- cli.cjs
#!/usr/bin/env node

'use strict';

Object.defineProperty(exports, '__esModule', { value: true });
...
```

It would be nice if someone could have a look at this or tell me if I should use other solutions for what I'm trying to accomplish.
Much love, Lone

**Comment by Julien-R44** [comment]
Hey! Yeah you are right. Nice catch. Thanks!
